name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:         # allow manual run if needed

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          curl -I https://demo-backend-by2h.onrender.com/docs
